version: '3'

services:
    node:
        container_name: node
        restart: 'unless-stopped'
        build:
            context: 'docker/node'
        volumes:
            - '.:/app'
        ports:
            - 80:80
            - 3001:3001
        env_file:
            - docker/.env_dev
